### ISSUE TITLE
Create ticket details view

### ISSUE THREAD

**Issue by saileru** [TUM-Dev/TicketCheck#2]
When the admin clicks on a ticket in the ticket list for an event, a Ticket Details Activity should be opened. It should display additional details of the ticket and provide a button to redeem it in case the user does not have his QR code, but only his ID.

**Comment by velev8** [comment]
Ticket Details Mockup:

<img width="276" alt="screen shot 2018-07-10 at 17 56 22" src="https://user-images.githubusercontent.com/38428686/42522040-7aebf264-846a-11e8-8a8c-3bfeabbb7ea9.png">

<img width="271" alt="screen shot 2018-07-10 at 17 56 48" src="https://user-images.githubusercontent.com/38428686/42522069-88c5581c-846a-11e8-8e5b-70704a8d4b9b.png">

<img width="271" alt="screen shot 2018-07-10 at 17 57 05" src="https://user-images.githubusercontent.com/38428686/42522081-8e496558-846a-11e8-8c67-5657f2e88852.png">

**Comment by schulzalexander** [comment]
Done in #13
