### ISSUE TITLE
Open issues

### ISSUE THREAD

**Issue by thellmund** [TUM-Dev/TicketCheck#39]
- [x] Show ticket type description (students, staff, etc.) in list view instead of ID
- [x] Show only event title in events list view
- [x] Move search to Toolbar
- [x] TicketDetailsFragment: Cancel button
- [x] TicketDetailsFragment: Ticket type description instead of ticket number
- [x] When refreshing while in search, one should stay in search

**Comment by kordianbruck** [comment]
@thellmund search is currently not working. After entering a term nothing happens. 

The other changes are really great. Love the new icon.

**Comment by kordianbruck** [comment]
Thanks! Looks good!
