### ISSUE TITLE
Admin should see total number of sold tickets for an event

### ISSUE THREAD

**Issue by saileru** [TUM-Dev/TicketCheck#4]
TS-C-4: As a cashier/admin, I want to be able to look up the total number of ticket sales for a certain event, so that event planning is facilitated.

A suggestion would be to include this on top of the ticket overview.

See https://github.com/TCA-Team/TumCampusApp/issues/805 for the initial discussion.

**Comment by Kailiangdong** [comment]
Is reviewing in #10

**Comment by saileru** [comment]
Closed in #10
