### ISSUE TITLE
Create Admin Ticket Overview

### ISSUE THREAD

**Issue by saileru** [TUM-Dev/TicketCheck#5]
The initial discussion and mockup can be seen in https://github.com/TCA-Team/TumCampusApp/issues/919

Make sure to implement the suggestions from the feedback:
- [x] Where is the scan button? Lets do a FAB for that
- [ ] I wouldn't show the TUM-ID nor the dates, that can be shown in a detail view
- [x] Search field on top is good
- [x] No paging/spinner in this screen please - at the entrance they only need to check for one event.

**Comment by Kailiangdong** [comment]
Reviewing in #10

**Comment by saileru** [comment]
Closed #10
