### ISSUE TITLE
Implement server calls in AdminDetailsActivity

### ISSUE THREAD

**Issue by saileru** [TUM-Dev/TicketCheck#6]
The sold tickets should be downloaded and saved locally, so that offline ticket check is possible.

Basically, the corresponding server calls need to be inserted in the Admin Ticket Overview which is implemented in #5.

Use the following API endpoint: 
api/event/ticket/sold/?

See https://github.com/TCA-Team/TumCampusApp/issues/950 for the initial ticket

Replace all other mock data in AdminDetailsActivity by actual server calls.
Respective statements are marked with TODOs

**Comment by schulzalexander** [comment]
Done in #12
