### ISSUE TITLE
Integrate Ticket Check Activity

### ISSUE THREAD

**Issue by saileru** [TUM-Dev/TicketCheck#8]
The corresponding server calls need to be integrated.

There is still some feedback left from https://github.com/TCA-Team/TumCampusApp/issues/905. However, I think most of the points are already considered in the mockups for #2 (detailed information, prominent checkin button).
Thus, I think that after the code is scanned successfully we could directly go to the Ticket Details Activity. The checkin could be done there. This would remove the need of the BottomSheet in the TicketScanActivity.
@velev8 @schulzalexander @Kailiangdong @kordianbruck Thoughts on that?

**Comment by schulzalexander** [comment]
Done in #13
